### ISSUE TITLE
Watch Ingress resouces and populate DNS

### ISSUE THREAD

**Issue by hbagdi** [calebdoxsey/kubernetes-cloudflare-sync#4]
Thank you for writing this sync app!

Currently, the domain(s) to bind the external IPs is via command-line flag.
@calebdoxsey , Would you be willing to accept a PR, whereby this Go application watches the Ingress resources and populates those DNS entries in Cloudflare?

**Comment by calebdoxsey** [comment]
Hi @hbagdi,

I'm not sure what you had in mind, but a full blown ingress controller would be out of scope for this small project. 

The goal of this project was mostly to serve as an example. If you have an idea for a more useful tool, feel free to use this code as a starting place and I can add a link in the readme to point people to it.

**Comment by yaacovCR** [comment]
I am thinking this may be orthogonal to what you are suggesting, but I successfully replaced the standalone nginx config described in the tutorial by @calebdoxsey with the [ingress-nginx](https://github.com/kubernetes/ingress-nginx) controller via the [stable/nginx-ingress](https://github.com/helm/charts/tree/master/stable/nginx-ingress) chart that is easily installable with [helm](https://helm.sh/).

The following was my yaml overrides for the installation of nginx-ingress, which I saved to myvalues.yaml. You can see that this mimics the deployment in the tutorial:

```
controller:
  kind: DaemonSet
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  daemonset:
    useHostPort: true
  service:
    type: ClusterIP
  extraArgs:
    report-node-internal-ip-address:
```

...and I then installed by running:

`helm install -f myvalues.yaml stable/nginx-ingress`

This was my ingress yaml which takes the place of the nginx configMap in the tutorial:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: MY_INGRESS_NAME_HERE
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: MY_TEST_HOSTNAME_HERE
    http:
      paths:
      - path: /MY_OPTIONAL_TEST_PATH_HERE
        backend:
          serviceName: MY_SERVICE_NAME_HERE
          servicePort: MY_SERVICE_PORT_HERE
```

With this setup, the nginx-ingress controller functions as a drop-in replacement to the nginx DaemonSet deployment in the tutorial, but none of this takes the place of the kubernetes-cloudflare-sync package. The ingress controller automatically updates nginx with new ingresses when new ingress objects are POSTED, but, as you can see from the above, the ingress objects themselves do not contain data about the node ip addresses and are orthogonal to the syncing of ip addresses of the nodes themselves with cloudflare.

**Comment by danopia** [comment]
I also configured the nginx ingress controller in my cluster. If you configure ingress-nginx correctly, the node IPs will be populated onto the Ingress objects by ingress-nginx. (The above config looks right, but I didn't verify it.) You can check if the node public IPs show up for your Ingress objects under Address:

```
$ kubectl describe ingress
Name:             ...
Address:          34.67.198.173,34.68.73.6,35.232.77.4
Default backend:  default-http-backend:80 (<none>)
```

If so, you can use [external-dns](https://github.com/kubernetes-incubator/external-dns) to sync the DNS records to cloudflare as well as many other dns providers based entirely on Ingress objects! external-dns is basically the 'more fleshed out' version of this project's spirit, as I think OP was looking for. Sadly, external-dns is not Watch based, so it has a somewhat noticeable reaction time compared to kubernetes-cloudflare-sync. ([PR pending](https://github.com/kubernetes-incubator/external-dns/pull/687))

I'm using this configuration now for updating records in Google Cloud DNS. Add cert-manager to the pile to get automatic letsencrypt based off Ingresses too. Bringing up new subdomains has never been so easy

**Comment by hbagdi** [comment]
I have moved to external-dns a long time ago to solve this problem. Thanks for the comments. Closing this now.

**Comment by donifer** [comment]
Sorry for reviving this thread!

@danopia Do you mind sharing your values.yaml (in case you are using the helm charts)? 🙏 

I have this for `nginx-ingress` as mentioned by @yaacovCR 
```
controller:
  name: controller
  image:
    repository: quay.io/kubernetes-ingress-controller/nginx-ingress-controller
    tag: '0.26.1'
  kind: DaemonSet
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  daemonset:
    useHostPort: true
  service:
    type: ClusterIP
  extraArgs:
    report-node-internal-ip-address: true
```

However when I do `kubectl get ing` I get an internal ip for the ingress 🤔 

```
❯ kubectl get ing
NAME               HOSTS             ADDRESS        PORTS   AGE
hello-kubernetes   example.com   10.12.15.143   80      3m
```

Not sure what I'm missing.


### Update
Figured out the chart now expects `controller.reportNodeInternalIp: false`
